#!/usr/bin/env python3
"""Regenerate The Food Pyramid's eight level scenes at the food-brick pitch.

A one-off authoring tool, kept so the scenes can be reproduced: it reads each
scene under assets/scenes/, keeps every brick's name, row, column and tag, and
writes the scene again with one prefab per food (the row's tier of the
pyramid), an armored twin for the foil-wrapped bricks, and every position
recomputed from the brick's name at the 64 x 32 cell and 4 px gap. The numbers
below mirror src/constants.rs; src/levels_tests.rs holds the shipped scenes to
those constants, so a change to one side fails the tests until the other
follows.

Before writing, the generator re-parses its own output and asserts, per scene,
the same name -> (row, col) set and the same tag multiset as its input: a
regeneration can move a brick but never lose, add or re-tag one.

Run from the repo root:

    python3 scripts/regenerate_levels.py          # rewrite the eight scenes
    python3 scripts/regenerate_levels.py --check  # exit 1 if any scene differs
                                                  # from a fresh generation
"""

import re
import sys
from collections import Counter
from pathlib import Path

SCENES = Path(__file__).resolve().parent.parent / "assets" / "scenes"

RENDER_UNIT = 80.0
BRICK_COLS = 10
BRICK_CELL_WIDTH = 64
BRICK_CELL_HEIGHT = 32
BRICK_GAP = 4
BRICK_TOP_Y = 240
BRICK_TOP_Y_2P = 90

# Row 0 is the top of the wall and of the pyramid; row 5 its base. Each food's
# sheet depth is its FoodSpec's in src/constants.rs — one depth per sheet,
# because the batcher draws a texture's batch whole.
FOODS_BY_ROW = [
    ("Donut", "donut", -0.35),
    ("Steak", "steak", -0.40),
    ("CheeseWheel", "cheese_wheel", -0.45),
    ("Baguette", "baguette", -0.50),
    ("Broccoli", "broccoli", -0.55),
    ("Watermelon", "watermelon", -0.60),
]

HEADER = """\
// {title_comment}
//
// Generated by scripts/regenerate_levels.py from the brick names and tags this
// file already held; re-run it (and its --check) after hand-editing a brick's
// position, or src/levels_tests.rs will say where the grid and the file disagree.
//
// Only bricks live in this scene; the counter, the walls, the tongs, the ball and
// the sensors are spawned by the game. The game re-instantiates this scene on
// every match start.
//
// Conventions the game relies on:
// - Entity names follow "brick_r{{row}}_c{{col}}" — the row digit drives the score
//   payout (see levels::brick_row_from_name), so keep names intact when editing.
// - A brick's food is its SpriteAnimation's sheet: each prefab below is one food,
//   and the row is its tier of the pyramid (donut at the top, watermelon at the
//   base). A sheet the game does not know falls back to the row's food.
// - Special bricks carry an EntityTag with '+'-joined tokens:
//     armored{{N}}      N total hits to destroy (2..=9); the brick wears the
//                     armored twin of its food's prefab, which plays "armored"
//     drop_multiball  drops a multiball candy when destroyed
//     drop_wrecking   drops a 10 s wrecking candy
//     drop_insiculous drops a candy granting BOTH effects
//   e.g. EntityTag(tag: "armored2+drop_wrecking"). No tag = plain brick.
// - Every brick's collider is its whole 64 x 32 cell and its sprite is the cell
//   drawn at 1x: scale (0.8, 0.4) x 80 = half_extents (32.0, 16.0) x 2.
// - Prefabs are authoring sugar; the editor's save pipeline flattens them.

"""


class RonParser:
    """Just enough RON for the level scenes: structs, tuples, lists, maps,
    strings, numbers, Some/None and bare identifiers, with // comments."""

    TOKEN = re.compile(
        r'\s*(?:(//[^\n]*)|("(?:[^"\\]|\\.)*")|(-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?)'
        r'|([A-Za-z_][A-Za-z_0-9]*)|([()\[\]{}:,]))'
    )

    def __init__(self, text):
        self.tokens = []
        position = 0
        while position < len(text):
            match = self.TOKEN.match(text, position)
            if not match:
                if text[position:].strip() == "":
                    break
                raise ValueError(f"unparsable RON near: {text[position:position + 40]!r}")
            position = match.end()
            comment, string, number, identifier, punctuation = match.groups()
            if comment is not None:
                continue
            if string is not None:
                self.tokens.append(("string", string[1:-1]))
            elif number is not None:
                self.tokens.append(("number", float(number)))
            elif identifier is not None:
                self.tokens.append(("identifier", identifier))
            else:
                self.tokens.append(("punctuation", punctuation))
        self.index = 0

    def peek(self):
        return self.tokens[self.index] if self.index < len(self.tokens) else (None, None)

    def take(self, expected=None):
        token = self.peek()
        if expected is not None and token[1] != expected:
            raise ValueError(f"expected {expected!r}, found {token!r}")
        self.index += 1
        return token

    def value(self):
        kind, text = self.peek()
        if kind == "string" or kind == "number":
            self.take()
            return text
        if text == "(":
            return self.parenthesised(None)
        if text == "[":
            return self.sequence("[", "]")
        if text == "{":
            return self.mapping()
        if kind == "identifier":
            self.take()
            if text == "None":
                return None
            if self.peek()[1] == "(":
                if text == "Some":
                    self.take("(")
                    inner = self.value()
                    self.take(")")
                    return inner
                return self.parenthesised(text)
            return text
        raise ValueError(f"unexpected token {self.peek()!r}")

    def parenthesised(self, name):
        """A struct `Name(field: value, ...)` or a tuple `(value, ...)`."""
        self.take("(")
        fields = {}
        items = []
        while self.peek()[1] != ")":
            kind, text = self.peek()
            following = self.tokens[self.index + 1] if self.index + 1 < len(self.tokens) else (None, None)
            if kind == "identifier" and following[1] == ":":
                self.take()
                self.take(":")
                fields[text] = self.value()
            else:
                items.append(self.value())
            if self.peek()[1] == ",":
                self.take(",")
        self.take(")")
        if fields or name is not None:
            return {"__struct__": name, **fields}
        return tuple(items)

    def sequence(self, opening, closing):
        self.take(opening)
        items = []
        while self.peek()[1] != closing:
            items.append(self.value())
            if self.peek()[1] == ",":
                self.take(",")
        self.take(closing)
        return items

    def mapping(self):
        self.take("{")
        entries = {}
        while self.peek()[1] != "}":
            key = self.value()
            self.take(":")
            entries[key] = self.value()
            if self.peek()[1] == ",":
                self.take(",")
        self.take("}")
        return entries


def parse_scene(text):
    parser = RonParser(text)
    scene = parser.value()
    if parser.index != len(parser.tokens):
        raise ValueError("trailing tokens after the scene")
    return scene


def brick_row_col(name):
    match = re.fullmatch(r"brick_r(\d+)_c(\d+)", name)
    if not match:
        raise ValueError(f"brick name {name!r} does not follow brick_r{{row}}_c{{col}}")
    return int(match.group(1)), int(match.group(2))


def component_tag(components):
    for component in components:
        if isinstance(component, dict) and component.get("__struct__") == "EntityTag":
            return component["tag"]
    return None


def bricks_of(scene):
    """Each brick as (name, row, col, tag), in the scene's order. The tag is
    resolved as the engine merges an entity: its prefab's components, then its
    overrides, then its inline components — the form an editor save writes, with
    the prefab flattened away. A scene holding anything but bricks is refused: the
    generator writes bricks only, and would silently drop the rest."""
    prefabs = scene.get("prefabs", {})
    bricks = []
    for entity in scene["entities"]:
        name = entity.get("name")
        if not name or not name.startswith("brick"):
            raise ValueError(f"scene entity {name!r} is not a brick; the generator would drop it")
        prefab = prefabs.get(entity.get("prefab")) if entity.get("prefab") else None
        tag = component_tag(entity.get("components", []))
        if tag is None:
            tag = component_tag(entity.get("overrides", []))
        if tag is None and prefab is not None:
            tag = component_tag(prefab.get("components", []))
        row, col = brick_row_col(name)
        bricks.append((name, row, col, tag))
    return bricks


def flattened(scene):
    """The scene as the editor's save writes it: every entity's prefab and
    overrides merged into inline components, no prefabs left."""
    prefabs = scene.get("prefabs", {})
    entities = []
    for entity in scene["entities"]:
        merged = {}
        prefab = prefabs.get(entity.get("prefab")) if entity.get("prefab") else None
        for layer in (prefab.get("components", []) if prefab else [], entity.get("overrides", []),
                      entity.get("components", [])):
            for component in layer:
                merged[component.get("__struct__")] = component
        entities.append({"name": entity.get("name"), "components": list(merged.values())})
    return {**scene, "prefabs": {}, "entities": entities}


def is_armored(tag):
    return tag is not None and any(
        token.strip().startswith("armored") for token in tag.split("+"))


def number(value):
    return f"{float(value):.1f}"


def brick_position(row, col, top_y):
    total_width = BRICK_COLS * BRICK_CELL_WIDTH + (BRICK_COLS - 1) * BRICK_GAP
    x = -(total_width - BRICK_CELL_WIDTH) / 2 + col * (BRICK_CELL_WIDTH + BRICK_GAP)
    y = top_y - row * (BRICK_CELL_HEIGHT + BRICK_GAP)
    return x, y


def prefab_name(row, armored):
    base = FOODS_BY_ROW[row][0]
    return f"{base}Armored" if armored else base


def prefab_text(row, armored):
    _, stem, depth = FOODS_BY_ROW[row]
    sheet = f"sprites/ai_pyramid_{stem}_64x32.png"
    clip = "armored" if armored else "intact"
    scale = f"({number(BRICK_CELL_WIDTH / RENDER_UNIT)}, {number(BRICK_CELL_HEIGHT / RENDER_UNIT)})"
    half_extents = f"({number(BRICK_CELL_WIDTH / 2)}, {number(BRICK_CELL_HEIGHT / 2)})"
    return (
        f'        "{prefab_name(row, armored)}": PrefabData(\n'
        f"            components: [\n"
        f"                Transform2D(scale: {scale}),\n"
        f'                Sprite(texture: "{sheet}", depth: {depth:.2f}, emissive: 0.0),\n'
        f'                SpriteAnimation(sheet: Some("{sheet}"), autoplay: Some("{clip}")),\n'
        f"                RigidBody(body_type: Static),\n"
        f"                Collider(shape: Box(half_extents: {half_extents}), friction: 0.0, restitution: 1.0),\n"
        f"            ],\n"
        f"        ),\n"
    )


def generate(scene_path, scene):
    """The scene text for `scene` (parsed from `scene_path`) at the food pitch."""
    coop = scene_path.name.endswith("_2p.scene.ron")
    top_y = BRICK_TOP_Y_2P if coop else BRICK_TOP_Y
    bricks = bricks_of(scene)
    for name, row, _, _ in bricks:
        if row >= len(FOODS_BY_ROW):
            raise ValueError(f"{scene_path.name}: {name} is below the pyramid's base row")

    used = sorted({(row, is_armored(tag)) for _, row, _, tag in bricks})
    scale = f"({number(BRICK_CELL_WIDTH / RENDER_UNIT)}, {number(BRICK_CELL_HEIGHT / RENDER_UNIT)})"

    lines = [HEADER.format(title_comment=f"{scene['name']} — The Food Pyramid's bricks.")]
    lines.append("SceneData(\n")
    lines.append(f'    name: "{scene["name"]}",\n')
    lines.append("    prefabs: {\n")
    for row, armored in used:
        lines.append(prefab_text(row, armored))
    lines.append("    },\n")
    lines.append("    entities: [\n")
    for name, row, col, tag in bricks:
        x, y = brick_position(row, col, top_y)
        overrides = f"Transform2D(position: ({number(x)}, {number(y)}), scale: {scale})"
        if tag is not None:
            overrides += f', EntityTag(tag: "{tag}")'
        lines.append(
            f'        EntityData(name: Some("{name}"), prefab: Some("{prefab_name(row, is_armored(tag))}"), '
            f"overrides: [{overrides}]),\n"
        )
    lines.append("    ],\n")
    lines.append(")\n")
    return "".join(lines)


def assert_same_bricks(scene_path, before, after):
    """The output holds exactly the input's bricks: names on the same cells, and
    the same tags as often."""
    cells_before = {name: (row, col) for name, row, col, _ in before}
    cells_after = {name: (row, col) for name, row, col, _ in after}
    if len(before) != len(cells_before) or cells_before != cells_after:
        raise AssertionError(f"{scene_path.name}: the regenerated bricks' names or cells differ")
    tags_before = Counter(tag for *_, tag in before)
    tags_after = Counter(tag for *_, tag in after)
    if tags_before != tags_after:
        raise AssertionError(
            f"{scene_path.name}: the tag multiset changed: {tags_before} -> {tags_after}")


def main(arguments):
    check = "--check" in arguments
    scene_paths = sorted(SCENES.glob("level*.scene.ron"))
    if len(scene_paths) != 8:
        print(f"expected the eight level scenes, found {len(scene_paths)}", file=sys.stderr)
        return 1

    differing = []
    for scene_path in scene_paths:
        original = scene_path.read_text()
        scene = parse_scene(original)
        regenerated = generate(scene_path, scene)
        assert_same_bricks(scene_path, bricks_of(scene), bricks_of(parse_scene(regenerated)))
        # An editor save flattens prefabs into inline components; the generator must
        # read that form as the engine does, or it would regenerate every brick bare.
        assert_same_bricks(scene_path, bricks_of(scene), bricks_of(flattened(scene)))
        if generate(scene_path, flattened(scene)) != regenerated:
            raise AssertionError(f"{scene_path.name}: an editor-flattened copy regenerates differently")
        if regenerated == original:
            continue
        differing.append(scene_path.name)
        if not check:
            scene_path.write_text(regenerated)

    if check:
        if differing:
            print("differ from a fresh generation: " + ", ".join(differing), file=sys.stderr)
            return 1
        print(f"all {len(scene_paths)} scenes equal a fresh generation")
        return 0
    print(f"regenerated {len(differing)} of {len(scene_paths)} scenes")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
